### ISSUE TITLE
Reading Data From Contentful

### ISSUE THREAD

**Issue by tud0r** [Khaledgarbaya/contentful-to-figma#4]
Conentful API keys do not seem to register in Figma plugin. After inputting API keys plugin stays stuck with message "Reading Data From Contentful" When dismissing plugin window and reopening the API Keys just configured have returned back to the default dummy API keys and you need to update with your own API keys again. Then same thing happens.

**Comment by tud0r** [comment]
Got this to pull in content however seems like the API key, environment variable and content type ID need to be typed each time to run the plugin??? Ideally the setting should be saved for each element in Figma that you configure to use the plugin.

**Comment by Khaledgarbaya** [comment]
with version 5 this should be fixed now
